import type { NextPage } from 'next'
import { Metadata } from 'next'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export const metadata: Metadata = {
  title: 'Next.js with App Router',
  description: 'Generated by create next app structured using the App Router'
}

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <main className={styles.main}>
        <h1>Buttons</h1>
      </main>

      <footer className={styles.footer}>
        <a
          href="/__repl"
          target="_blank"
          rel="noopener noreferrer"
        >
          Built by
          <span className={styles.logo}>
            <Image src="/replit.svg" alt="Replit Logo" width={20} height={18} />
          </span>
          Drashti Trivedi
        </a>
      </footer>
    </div>
  )
}

export default Home
